### ISSUE TITLE
no restx route found for GET /1/person/_init

### ISSUE THREAD

**Issue by mvplove123** [dadoonet/legacy-search#11]
hi,during  the  time ,i want  to learn elasticsearch,and  i found your code, i git  clone  it  ,and  deploy it  ,when i click inject buttoon ,it  does  not  work ,i see this problem ,i don't  know  how to solve it  ,please give me   some advice .

problem:
no restx route found for GET /1/person/_init
go to http://qhotel.tao.qunarman.com:8080/api/@/ui/api-docs/ for API documentation
## routes:

GET /@/pages => restx-admin#AdminPagesResource#findPages
GET /@/api-docs/schemas/{fqcn} => restx-admin#JsonSchemaResource#getJsonSchema
GET /@/specs => restx-admin#SpecsResource#findSpecsForOperation
GET /@/specs/{id} => restx-admin#SpecsResource#getSpecById
PUT /@/specs/{id}/wts/{wtsIndex}/then => restx-admin#SpecsResource#updateSpecThenHttp
GET /@/config/elements => restx-admin#ConfigResource#findConfigElements
GET /@/metrics => restx-admin#MetricsResource#metrics
GET /@/health-checks => restx-admin#MetricsResource#healthChecks
GET /@/thread-dump => restx-admin#MetricsResource#threadDump
GET /@/ui/monitor/\* => MonitorUIRoute

**Comment by dadoonet** [comment]
Try GET /api/1/person/_init

BTW there is an init tab in the interface now.
