### ISSUE TITLE
Update to restx 0.35-rc1

### ISSUE THREAD

**Issue by dimowski** [dadoonet/legacy-search#54]
Hello David! I was trying to run `00-legacy` branch, and maven couldn't find `0.35-SNAPSHOT` version of `io.restx`. I am not sure if I used the right maven repositories, but there is only `0.35-rc1`. And in order to run application, I had to switch to `0.34.1` version of `io.restx` and add two more dependencies to pom.xml:  `jackson-annotations`, `jackson-core`. Am I doing something wrong?

**Comment by dadoonet** [comment]
Yeah. It's because restx just released its 0.35 so it's not available as a snapshot anymore.

I'll fix it

**Comment by dadoonet** [comment]
Fixed now. Thanks for reporting! :D
